// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Represents error object.
// Ref: #/components/schemas/Error
type Error struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptPrompt returns new OptPrompt with value set to v.
func NewOptPrompt(v Prompt) OptPrompt {
	return OptPrompt{
		Value: v,
		Set:   true,
	}
}

// OptPrompt is optional Prompt.
type OptPrompt struct {
	Value Prompt
	Set   bool
}

// IsSet returns true if OptPrompt was set.
func (o OptPrompt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPrompt) Reset() {
	var v Prompt
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPrompt) SetTo(v Prompt) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPrompt) Get() (v Prompt, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPrompt) Or(d Prompt) Prompt {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Prompt
type Prompt struct {
	Prompt string `json:"prompt"`
}

// GetPrompt returns the value of Prompt.
func (s *Prompt) GetPrompt() string {
	return s.Prompt
}

// SetPrompt sets the value of Prompt.
func (s *Prompt) SetPrompt(val string) {
	s.Prompt = val
}

// Ref: #/components/schemas/VisualizableData
type VisualizableData struct {
	VisualizableData string `json:"visualizableData"`
}

// GetVisualizableData returns the value of VisualizableData.
func (s *VisualizableData) GetVisualizableData() string {
	return s.VisualizableData
}

// SetVisualizableData sets the value of VisualizableData.
func (s *VisualizableData) SetVisualizableData(val string) {
	s.VisualizableData = val
}
